"use client";

import { useState, useEffect } from "react";

import { hardConfig } from "../main/config/hard";
import { formatLightningAuth } from "../utils/lnurl";

const maxNetworkRequestsFailures = 3;

/**
 * A React hook that, on mount, will trigger an API request and create a new Lightning auth session.
 * Thereafter, it'll poll the API and checks if the Lightning auth QR has been scanned.
 * If enough time elapses without a sign in attempt, the Lightning auth session will be refreshed.
 * Once a success status is received from polling, the user will be redirected to the `redirectUri`.
 *
 * @param {String} redirectUri - the `redirect_uri` query param generated by `next-auth`
 * @param {String} state - the `state` query param generated by `next-auth`
 *
 * @returns {Object}
 * @returns {String} lnurl - the raw LNURL, should be made available for copy-pasting
 * @returns {String} qr - a url pointing the lnurl-auth QR Code image, should be used in the src prop of img tags
 * @returns {String} button - a deep-link that will open in Lightning enabled wallets, should be used in the href prop of anchor tags
 */
export function useLightningAuth({
  redirectUri,
  state,
}: {
  redirectUri: string;
  state: string;
}): {
  lnurl: string | null;
  qr: string;
  button: string;
} {
  const [lnurl, setUrl] = useState<string | null>(null);

  useEffect(() => {
    let session: {
      k1: string;
      lnurl: string;
      pollInterval: number;
      createInterval: number;
    } | null;
    let pollTimeoutId: NodeJS.Timeout | undefined;
    let createIntervalId: NodeJS.Timeout | undefined;
    let networkRequestCount: number = 0;
    let errorUrl: string | undefined;
    const pollController = new AbortController();
    const createController = new AbortController();

    // cleanup when the hook unmounts of polling is successful
    const cleanup = () => {
      clearTimeout(pollTimeoutId);
      clearInterval(createIntervalId);
      pollController.abort();
      createController.abort();
    };

    // redirect user to error page if something goes wrong
    function error(e: any) {
      console.error(e);
      if (errorUrl) {
        window.location.replace(errorUrl);
      } else {
        // if no errorUrl exists send to defaul `next-auth` error page
        const params = new URLSearchParams();
        params.append("error", "OAuthSignin");
        window.location.replace(`/api/auth/error?${params.toString()}`);
      }
    }

    // poll the api to see if the user has successfully authenticated
    function poll() {
      if (!session || !session.k1) return;
      const k1 = session.k1;

      const params = new URLSearchParams({ k1 });

      return fetch(hardConfig.apis.poll, {
        method: "POST",
        headers: { "content-type": "application/x-www-form-urlencoded" },
        body: params,
        cache: "default",
        signal: pollController.signal,
      })
        .then((r) => {
          if (r.status === 410) {
            // if resource not found throw error immediately,
            // this means the user's auth session has been deleted.
            networkRequestCount = maxNetworkRequestsFailures;
          }
          return r.json();
        })
        .catch((e) => {
          // if there are more than X network errors, then trigger redirect
          networkRequestCount++;
          if (networkRequestCount >= maxNetworkRequestsFailures) {
            pollTimeoutId = setTimeout(poll, session!.pollInterval);
            throw e;
          }
        })
        .then((d) => {
          if (d && d.error) {
            if (d.url) errorUrl = d.url;
            throw new Error(d.message || d.error);
          }

          if (d) networkRequestCount = 0;
          if (d && d.message) throw new Error(d.message);
          pollTimeoutId = setTimeout(poll, session!.pollInterval);

          if (d && d.success) {
            cleanup();
            let url = new URL(redirectUri);
            url.searchParams.append("state", state);
            url.searchParams.append("code", k1);
            window.location.replace(url);
          }
        })
        .catch((e) => {
          if (!pollController.signal.aborted) {
            error(e);
          }
        });
    }

    // create a new lnurl and set it to state
    function create() {
      const params = new URLSearchParams({ state });
      if (session && session.k1) {
        params.append("k1", session.k1);
      }
      return fetch(hardConfig.apis.create, {
        method: "POST",
        headers: { "content-type": "application/x-www-form-urlencoded" },
        body: params,
        cache: "default",
        signal: createController.signal,
      })
        .then((r) => r.json())
        .then((d) => {
          if (d && d.error) {
            if (d.url) errorUrl = d.url;
            throw new Error(d.message || d.error);
          }

          session = d;
          if (!session || !session.lnurl) return;

          // setup intervals and create first qr code
          pollTimeoutId = setTimeout(poll, session?.pollInterval);
          createIntervalId = setInterval(create, session?.createInterval);

          setUrl(session?.lnurl || null);
        })
        .catch((e) => {
          if (!createController.signal.aborted) {
            error(e);
          }
        });
    }

    create();

    return () => cleanup();
  }, []);

  const { qr, button } = formatLightningAuth(lnurl);

  return { lnurl, qr, button };
}
